language: python

python:
 - 3.6
 - 3.7

matrix:
  include:
  - python: 3.6
  - python: 3.7
    sudo: required
    dist: xenial

install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover
